### ISSUE TITLE
isSpace throws on Asian characters

### ISSUE THREAD

**Issue by bklaric** [purescript-contrib/purescript-unicode#20]
Minimal repro in REPL

    import Prelude

    import Data.Char.Unicode (isHexDigit, isPrint, isSpace)
    import Data.Foldable (all)
    import Data.String.CodeUnits (toCharArray)

    "カタカナ" # toCharArray # all (not <<< isSpace)

Fails with

    /home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/Data.Char.Unicode.Internal/index.js:6822
            if (v.start >= v1.start && v.start < (v1.start + v1.length | 0)) {
                            ^

    TypeError: Cannot read property 'start' of undefined
        at /home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/Data.Char.Unicode.Internal/index.js:6822:27
        at $tco_loop (/home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/Data.Char.Unicode.Internal/index.js:6793:51)
        at /home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/Data.Char.Unicode.Internal/index.js:6810:43
        at /home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/Data.Char.Unicode.Internal/index.js:6815:29
        at /home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/Data.Char.Unicode.Internal/index.js:6844:60
        at Object.uIswspace (/home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/Data.Char.Unicode.Internal/index.js:6882:62)
        at Object.isSpace (/home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/Data.Char.Unicode/index.js:2006:39)
        at /home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/$PSCI/index.js:13:31
        at /home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/Control.Semigroupoid/index.js:18:22
        at /home/bklaric/Documents/PureScript/purescript-team-tavern-server/.psci_modules/node_modules/Data.Foldable/index.js:467:75

Replacing `isSpace` with `isPrint` or `isHexDigit` works fine.

PureScript 0.12.0
Pulp 12.3.0
purescript-unicode 4.0.1

**Comment by maxdeviant** [comment]
This is no longer reproducible in the latest version of the library.

Here is the original code, updated to use `CodePoint`s instead of `Char`s:

```purs
import Prelude

import Data.CodePoint.Unicode (isHexDigit, isPrint, isSpace)
import Data.Foldable (all)
import Data.String.CodePoints (toCodePointArray)

"カタカナ" # toCodePointArray # all (not <<< isSpace)
```

In the REPL:

```
λ spago repl
PSCi, version 0.14.3
Type :? for help

> import Prelude
> import Data.CodePoint.Unicode (isHexDigit, isPrint, isSpace)
> import Data.Foldable (all)
> import Data.String.CodePoints (toCodePointArray)
> "カタカナ" # toCodePointArray # all (not <<< isSpace)
true
```
