### ISSUE TITLE
Rename digitToInt as hexDigitToInt, create new decimal-only digitToInt

### ISSUE THREAD

**Issue by milesfrain** [purescript-contrib/purescript-unicode#25]
We have these functions:
* `isDigit` - matches `0..9`
* `isHexDigit` - matches `0..9, a..f, A..F`
* `digitToInt` - converts **hex** digits `0..9, a..f, A..F` to `0..15`

Would it make more sense to rename `digitToInt` to `hexDigitToInt` and create a new `digitToInt` that only converts **decimal** digits:
* `digitToInt` - converts decimal digits `0..9` to `0..9`
* `hexDigitToInt` - converts hex digits `0..9, a..f, A..F` to `0..15`

This issue came up in this slack discussion:
https://functionalprogramming.slack.com/archives/C717K38CE/p1589481039128200

**Comment by thomashoneyman** [comment]
@milesfrain I'd be happy to accept this, though ideally we would do this with a deprecation cycle to avoid breaking existing code (warning instead).

**Comment by milesfrain** [comment]
Is it possible to do a deprecation cycle when modifying (rather than removing) an existing function - `digitToInt` in this case?

We could instead remove/deprecate `digitToInt` and add `decDigitToInt`, so we'd have this pair:
- `decDigitToInt` - converts decimal digits `0..9` to `0..9`
- `hexDigitToInt` - converts hex digits `0..9, a..f, A..F` to `0..15`

**Comment by thomashoneyman** [comment]
I like the option you’ve suggested, dec/hexDigitToInt, though it differs from isDigit. I’m open to other alternatives though. This seems like an appropriately conservative way to change the library.
