### ISSUE TITLE
The docs for digitToInt say that it throws when it doesn't.

### ISSUE THREAD

**Issue by philderbeast** [purescript-contrib/purescript-unicode#6]
The docs for [digitToInt](https://pursuit.purescript.org/search?q=digitToInt) say that it throws when it doesn't ...

> Both upper- and lower-case A through F are converted as well, to 10..15.
> Anything else throws an exception

```
> import Data.Char.Unicode
> :t digitToInt
Char -> Maybe Int

> digitToInt 'G'
Nothing
```

**Comment by cdepillabout** [comment]
@philderbeast Thanks for reporting this.  I copied the documentation from the Haskell module and I must have missed that.

Would you be able to send a PR fixing it?

**Comment by philderbeast** [comment]
The [updated docs](https://pursuit.purescript.org/packages/purescript-unicode/2.0.2/docs/Data.Char.Unicode) on Pursuit.
