### ISSUE TITLE
Fix test dependencies for 0.11

### ISSUE THREAD

**Issue by cdepillabout** [purescript-contrib/purescript-unicode#9]
`purescript-spec` needs to be updated for 0.11 (https://github.com/owickstrom/purescript-spec/pull/45).  When it is updated, we can update the test dependencies for `purescript-unicode` as mentioned in #8.

**Comment by cdepillabout** [comment]
It should also roll back #10.

Looping in @paf31 just in case.

**Comment by paf31** [comment]
👍 Thanks
